# Generated by Django 4.2.30 on 2026-09-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='1-5 代表周一到周五')),
                ('period', models.IntegerField(help_text='第几节课')),
                ('is_locked', models.BooleanField(default=False, help_text='锁定后不参与自动重排')),
                ('is_conflict', models.BooleanField(default=False)),
                ('conflict_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.class')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('original_teacher', models.ForeignKey(blank=True, help_text='如果是代课，记录原教师', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_for', to='core.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'ordering': ['semester', 'day_of_week', 'period'],
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_source', to='scheduling.scheduleentry')),
                ('entry2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_target', to='scheduling.scheduleentry')),
                ('requesting_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='core.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('target_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='core.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_token', models.CharField(db_index=True, help_text='客户端幂等令牌，同一令牌重复或并发提交只生效一次', max_length=64, unique=True)),
                ('entry1_id_snapshot', models.IntegerField(help_text='提交时条目1的ID快照')),
                ('entry2_id_snapshot', models.IntegerField(help_text='提交时条目2的ID快照')),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', '交换成功'), ('rejected', '试算拒绝')], max_length=20)),
                ('conflicts', models.JSONField(default=list, help_text='试算拒绝时导致拒绝的冲突明细；成功时保存重算后的冲突快照')),
                ('result', models.JSONField(default=dict, help_text='交换成功后的两条条目结果快照')),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_records_first', to='scheduling.scheduleentry')),
                ('entry2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_records_second', to='scheduling.scheduleentry')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_records', to='core.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_record', to='scheduling.scheduleentry')),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='core.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('teacher', '教师冲突'), ('classroom', '教室冲突'), ('class', '班级冲突')], max_length=20)),
                ('day_of_week', models.IntegerField()),
                ('period', models.IntegerField()),
                ('involved_entries', models.JSONField(default=list)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='core.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'ordering': ['semester', 'class_id'],
                'unique_together': {('class_id', 'course', 'teacher', 'semester')},
            },
        ),
    ]
